apiVersion: v1
kind: Service
metadata:
  name: student-web
spec:
  selector:
    app: app-student-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30559
  type: NodePort